### PR TITLE
adding Yprey to the owasp collection

### PR DESCRIPTION
**Pull request by yrprey**
The website https://yrprey.com/ does not host a vulnerable application itself. Instead, it serves as a landing page promoting vulnerable applications that are accessible on GitHub. On GitHub, users can opt to download either the Docker container version or the source code and set it up in their local environment. Thus, users have two download options available.

The sole purpose of the https://yrprey.com/ page is to advertise and promote these vulnerable applications, which can be found on GitHub.

For downloading the source code, please visit:

Backend: https://github.com/yrprey/yrprey-backend
Frontend: https://github.com/yrprey/yrprey-frontend
For the container version, visit: https://github.com/yrprey/yrprey-application

### CODE REVIEW

**Comment by kingthorin** [comment]
Valid types of references are:

"guide",
"download",
"docker",
"downloads",
"announcement",
"live",
"demo",
"preview"

**Comment by yrprey** [comment]
Thank you, I will check.

**Comment by kingthorin** [comment]
Please revert the changes (formatting) unrelated to your addition.

**Comment by yrprey** [comment]
Adjusted!

**Pull request merged**
