### PR TITLE
Update to include OWASP-SKF Labs

### PR DESCRIPTION
**Pull request by blabla1337**
update to include the SKF Labs

### CODE REVIEW

**Comment by blabla1337** [comment]
LoL, maybe its to early for me but I cannot see what the problem is...

**Comment by kingthorin** [comment]
"Labs" doesn't match a reference name: https://github.com/OWASP/OWASP-VWAD/blob/f4cfa6a16022996aa7334ea6d2a9dafc8af2dcc0/schema.json#L91-L104

**Comment by blabla1337** [comment]
Thanks for the remark ^^ was to early for me and needed more coffee I guess ^^

**Comment by kingthorin** [comment]
No problem, thanks for the contribution!

**Review by kingthorin — APPROVED** [review]

**Pull request merged**
