### PR TITLE
Add various Vuln Apps

### PR DESCRIPTION
**Pull request by kingthorin**
* online.json
  - Fix previously missing comma
  - Added DVSA
  - Added OWASP Serverless Goat (Fixes OWASP/OWASP-VWAD#58)
  - Added AuthLab

* offline.json
  - Fix formatting of some empty array elements
  - Added play-webgoat (Fixes OWASP/OWASP-VWAD#53)
  - Added DVSA (Fixes OWASP/OWASP-VWAD#55)
  - Added CloudGoat (Fixes OWASP/OWASP-VWAD#55)
  - Added DVFaaS (Fixes OWASP/OWASP-VWAD#57)
  - Added DSVW (Fixes OWASP/OWASP-VWAD#59)
  - Added DjangoGoat (Fixes OWASP/OWASP-VWAD#60)
  - Added AuthLab (Fixes OWASP/OWASP-VWAD#61)
  - Added Vulnerable SAML App (Fixes OWASP/OWASP-VWAD#63)

### CODE REVIEW

**Comment by kingthorin** [comment]
@raulsiles look good?

**Comment by kingthorin** [comment]
@OWASPFoundation anyone out there?

**Comment by raulsiles** [comment]
> @raulsiles look good?

Sorry about the delay in my response. Thanks for all the fixes and updates!

My only suggestion, as this is how we intended it to be from the early start, is to sort out the new entries based in the application name. They are supposed to appear alphabetically ordered (although probably we need a whole review to double check if some other entries are out of order).

**Comment by kingthorin** [comment]
Okay I'll see what I can do.

**Comment by kingthorin** [comment]
@raulsiles I added a separate commit for the sorting (of all 3 files), to make the review easier. However, given how github diffs them I'm not sure it'll be that easy to review.

Either way, let me know what you think or if there's something else I can do.

**Comment by raulsiles** [comment]
Thanks for taking the time to clean it up! Great contribution!

**Pull request merged**
