### PR TITLE
Format adjustments

### PR DESCRIPTION
**Pull request by kingthorin**
vm-iso.json
* Addressed trailing commas on Notes element `"Notes": null,` > `"Notes": null`
* Adjusted references element as discussed in OWASP/OWASP-VWAD#40
* Per https://github.com/OWASP/OWASP-VWAD/issues/40#issuecomment-343909509 change all property names to lower case as well.

online.json
* Added references element as discussed in OWASP/OWASP-VWAD#40 (moved any references from notes to references).
* Per https://github.com/OWASP/OWASP-VWAD/issues/40#issuecomment-343909509 change all property names to lower case as well.
* Repointed hackazon to rapid7 (from NTOObjectives)

offline.json
* Added references element as discussed in OWASP/OWASP-VWAD#40.
* Per https://github.com/OWASP/OWASP-VWAD/issues/40#issuecomment-343909509 change all property names to lower case as well.

All three:
* Per https://github.com/OWASP/OWASP-VWAD/pull/52#issuecomment-405829305 & https://github.com/OWASP/OWASP-VWAD/pull/52#issuecomment-405850746 the technology element was changed to an array of strings.

Fixes OWASP/OWASP-VWAD#40

### CODE REVIEW

**Comment by kingthorin** [comment]
I guess based on the github diff I totally reformatted everything. I can try to wind the formatting back if needed.

I'm happy to leave this open and address the other two file as well, or I can open separate PRs for them.

**Comment by kingthorin** [comment]
> BTW, the third entry in "offline" has two references in a single line.

Thanks, it snuck by me somehow. Adjustment coming.

**Comment by kingthorin** [comment]
Anyone else got feedback? Is this good to go?

**Comment by kingthorin** [comment]
Anyone out there? :smiley:

**Comment by kingthorin** [comment]
Approved? Merged? :+1:

**Comment by psiinon** [comment]
Just one suggestion - as we're reformatting, why not make the technology a list, rather than a comma separated string?

**Comment by raulsiles** [comment]
Originally, the technology reflected the main technology the web app was based on. However, for some entries we already mention several technologies, so I'm fine with making it a list and have more future flexibility to provide more details for each entry.

**Comment by kingthorin** [comment]
Sure, I'll dig into that.

**Comment by kingthorin** [comment]
For some reason my browser is showing 3 commits in the conversation view [1] on github but only one in the commit view [2]. According to my local git history the github commit tab is correct.

[1]
image
[2]
image

**Comment by thc202** [comment]
That's because they referenced this PR in the commit message.

**Comment by kingthorin** [comment]
Ugh.....ok well at least it makes sense now. Thanks!

**Comment by kingthorin** [comment]
Look good to go now?

**Comment by psiinon** [comment]
@raulsiles you ok with this now?

**Comment by raulsiles** [comment]
I'm ok with the new format. Should we merge the PR and use it as the new format?

**Comment by psiinon** [comment]
Yeah :)

**Comment by raulsiles** [comment]
@kingthorin Thank you! for your contributions.

**Pull request merged**
