### PR TITLE
Add Gin & Juice Shop.

### PR DESCRIPTION
**Pull request by drfoofoo**

### CODE REVIEW

**Review by kingthorin — COMMENTED** [review]
Looks good but are there really no references? An announcement? A guide? Etc

**Comment by drfoofoo** [comment]
Can't find much. There's this blog post: https://portswigger.net/blog/gin-and-juice-shop-put-your-scanner-to-the-test which I could add under 'announcement'?

**Comment by kingthorin** [comment]
Sure that seems good

**Review by kingthorin — APPROVED** [review]

**Comment by drfoofoo** [comment]
Ace. Thanks @kingthorin

**Pull request merged**
