### PR TITLE
Revert "update to Rapid7 products"

### PR DESCRIPTION
**Pull request by dyna-dot**
Reverts OWASP/OWASP-VWAD#54

### CODE REVIEW

**Comment by kingthorin** [comment]
@dyna-dot why?

**Comment by kingthorin** [comment]
@dyna-dot why?

**Comment by raulsiles** [comment]
@dyna-dot May you please provide a reason/description for this commit, as @kingthorin requested?

**Comment by bkimminich** [comment]
Changing the name back into `Web Scanner Test Site` seems like a good idea. I'm also not sure if the entire list of technologies used on the page makes sense here. If we keep it, we might want to add some more info to other apps as well.

**Comment by kingthorin** [comment]
Let's close this and I'll submit one that fixes the missing comma in the tech list and uses the verbose name.

**Pull request closed without merging**
