### PR TITLE
Added Damn Vulnerable RESTaurant

### LINKED ISSUE #203: Add the Damn Vulnerable RESTaurant
https://github.com/theowni/Damn-Vulnerable-RESTaurant-API-Game

I know I should PR it .. but not got the time right now 😉

### PR DESCRIPTION
**Pull request by dsopas**
Closes #203

### CODE REVIEW

**Review by kingthorin — COMMENTED** [review]
Why is there so much other change in this PR?

**Comment by dsopas** [comment]
Didn't noticed that. Maybe because I used another JSON order by name tool.
I just confirmed it using jq:

$ jq length collection.json 
144
$ jq length collection_david.json 
145

**Comment by kingthorin** [comment]
K, I'll fix it

**Comment by kingthorin** [comment]
https://github.com/kingthorin/OWASP-VWAD/pull/207

**Pull request closed without merging**
